function [ret] = external_sources()
    l = @(x)( (abs(x(:,1)    ) < eps) );
    r = @(x)( (abs(x(:,1) - 1) < eps) );
    b = @(x)( (abs(x(:,2)    ) < eps) );
    t = @(x)( (abs(x(:,2) - 1) < eps) );
    
    
    ret = cell(4, 1);
    ret{1} = @(x)(...
        2 .* l(x) +...
        exp(-x(:,1)).* b(x) + ...
        exp(-x(:,1)).* t(x) + ...
        (-exp(-1)) .* r(x) ...
    );


    ret{2} = @(x)(...
        1 .* l(x) + ...
        (1 + cos(4*pi*x(:,1))) .* b(x) + ...
        (1 + sin(4*pi*x(:,1))) .* t(x) + ...
        (-cos(4*pi*x(:,1))) .* r(x)...
        );
    
    ret{3} = @(x)(...
        (-cos(4*pi*x(:,2))) .* l(x) + ...
        (2 + sin(4*pi*x(:,1))) .* b(x) + ...
        (2 - cos(4*pi*x(:,1))) .* t(x) + ...
        (exp(-x(:,2))) .* r(x)...
    );
    
    ret{4} = @(x)(...
        5 .* l(x) + ...
        10 .* b(x) + ...
        12 .* t(x) + ...
        23 .* r(x)...
    );
end

